server:
  tomcat:
    basedir: /Users/fengcheng/data/temp
spring:
  redis:
    host: localhost
    password:
    port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/fast-api?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

sys:
  startCleanCache: true
  fileUploadPath: /Users/fengcheng/data/uploads/
  fileAccessPath: http://127.0.0.1/uploads/

oss:
  bucketName: fast-api-dev
  fileDomain: http://fast-api.oss-cn-beijing.aliyuncs.com/
